version: 0.0
os: linux
files:
  - source:  /
    destination: /var/www/prod
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/prod-deploy.sh
      timeout: 60
      runas: ubuntu
